package modelo;
// Generated 8/11/2017 03:24:52 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Rolfuncionalidad generated by hbm2java
 */
@Entity
@Table(name="rolfuncionalidad"
    ,schema="vortal"
)
public class Rolfuncionalidad  implements java.io.Serializable {


     private int rolfunId;
     private Funcionalidad funcionalidad;
     private Rol rol;
     private Date rolfunFecharegistro;

    public Rolfuncionalidad() {
    }

    public Rolfuncionalidad(int rolfunId, Funcionalidad funcionalidad, Rol rol, Date rolfunFecharegistro) {
       this.rolfunId = rolfunId;
       this.funcionalidad = funcionalidad;
       this.rol = rol;
       this.rolfunFecharegistro = rolfunFecharegistro;
    }
   
     @Id 

    
    @Column(name="rolfun_id", unique=true, nullable=false)
    public int getRolfunId() {
        return this.rolfunId;
    }
    
    public void setRolfunId(int rolfunId) {
        this.rolfunId = rolfunId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fun_id", nullable=false)
    public Funcionalidad getFuncionalidad() {
        return this.funcionalidad;
    }
    
    public void setFuncionalidad(Funcionalidad funcionalidad) {
        this.funcionalidad = funcionalidad;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="rol_id", nullable=false)
    public Rol getRol() {
        return this.rol;
    }
    
    public void setRol(Rol rol) {
        this.rol = rol;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="rolfun_fecharegistro", nullable=false, length=22)
    public Date getRolfunFecharegistro() {
        return this.rolfunFecharegistro;
    }
    
    public void setRolfunFecharegistro(Date rolfunFecharegistro) {
        this.rolfunFecharegistro = rolfunFecharegistro;
    }




}


