package modelo;
// Generated 8/11/2017 03:24:52 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name="usuario"
    ,schema="vortal"
    , uniqueConstraints = @UniqueConstraint(columnNames="usu_usuario") 
)
public class Usuario  implements java.io.Serializable {


     private String usuDocumento;
     private String usuNombre;
     private String usuUsuario;
     private String usuClave;
     private String usuCorreo;
     private Date usuFecharegistro;
     private String usuPreguntaregistro;
     private String usuRespuestapregunta;
     private String usuTema;
     private Set usuariorols = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(String usuDocumento, String usuNombre, String usuUsuario, String usuClave, String usuCorreo, Date usuFecharegistro, String usuPreguntaregistro, String usuRespuestapregunta) {
        this.usuDocumento = usuDocumento;
        this.usuNombre = usuNombre;
        this.usuUsuario = usuUsuario;
        this.usuClave = usuClave;
        this.usuCorreo = usuCorreo;
        this.usuFecharegistro = usuFecharegistro;
        this.usuPreguntaregistro = usuPreguntaregistro;
        this.usuRespuestapregunta = usuRespuestapregunta;
    }
    public Usuario(String usuDocumento, String usuNombre, String usuUsuario, String usuClave, String usuCorreo, Date usuFecharegistro, String usuPreguntaregistro, String usuRespuestapregunta, String usuTema, Set usuariorols) {
       this.usuDocumento = usuDocumento;
       this.usuNombre = usuNombre;
       this.usuUsuario = usuUsuario;
       this.usuClave = usuClave;
       this.usuCorreo = usuCorreo;
       this.usuFecharegistro = usuFecharegistro;
       this.usuPreguntaregistro = usuPreguntaregistro;
       this.usuRespuestapregunta = usuRespuestapregunta;
       this.usuTema = usuTema;
       this.usuariorols = usuariorols;
    }
   
     @Id 

    
    @Column(name="usu_documento", unique=true, nullable=false, length=24)
    public String getUsuDocumento() {
        return this.usuDocumento;
    }
    
    public void setUsuDocumento(String usuDocumento) {
        this.usuDocumento = usuDocumento;
    }

    
    @Column(name="usu_nombre", nullable=false, length=124)
    public String getUsuNombre() {
        return this.usuNombre;
    }
    
    public void setUsuNombre(String usuNombre) {
        this.usuNombre = usuNombre;
    }

    
    @Column(name="usu_usuario", unique=true, nullable=false, length=124)
    public String getUsuUsuario() {
        return this.usuUsuario;
    }
    
    public void setUsuUsuario(String usuUsuario) {
        this.usuUsuario = usuUsuario;
    }

    
    @Column(name="usu_clave", nullable=false, length=124)
    public String getUsuClave() {
        return this.usuClave;
    }
    
    public void setUsuClave(String usuClave) {
        this.usuClave = usuClave;
    }

    
    @Column(name="usu_correo", nullable=false, length=124)
    public String getUsuCorreo() {
        return this.usuCorreo;
    }
    
    public void setUsuCorreo(String usuCorreo) {
        this.usuCorreo = usuCorreo;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="usu_fecharegistro", nullable=false, length=22)
    public Date getUsuFecharegistro() {
        return this.usuFecharegistro;
    }
    
    public void setUsuFecharegistro(Date usuFecharegistro) {
        this.usuFecharegistro = usuFecharegistro;
    }

    
    @Column(name="usu_preguntaregistro", nullable=false, length=224)
    public String getUsuPreguntaregistro() {
        return this.usuPreguntaregistro;
    }
    
    public void setUsuPreguntaregistro(String usuPreguntaregistro) {
        this.usuPreguntaregistro = usuPreguntaregistro;
    }

    
    @Column(name="usu_respuestapregunta", nullable=false, length=224)
    public String getUsuRespuestapregunta() {
        return this.usuRespuestapregunta;
    }
    
    public void setUsuRespuestapregunta(String usuRespuestapregunta) {
        this.usuRespuestapregunta = usuRespuestapregunta;
    }

    
    @Column(name="usu_tema", length=100)
    public String getUsuTema() {
        return this.usuTema;
    }
    
    public void setUsuTema(String usuTema) {
        this.usuTema = usuTema;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="usuario")
    public Set getUsuariorols() {
        return this.usuariorols;
    }
    
    public void setUsuariorols(Set usuariorols) {
        this.usuariorols = usuariorols;
    }




}


