package modelo;
// Generated 8/11/2017 03:24:52 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Usuariorol generated by hbm2java
 */
@Entity
@Table(name="usuariorol"
    ,schema="vortal"
)
public class Usuariorol  implements java.io.Serializable {


     private int usurolId;
     private Rol rol;
     private Usuario usuario;
     private Date usurolFecharegistro;

    public Usuariorol() {
    }

    public Usuariorol(int usurolId, Rol rol, Usuario usuario, Date usurolFecharegistro) {
       this.usurolId = usurolId;
       this.rol = rol;
       this.usuario = usuario;
       this.usurolFecharegistro = usurolFecharegistro;
    }
   
     @Id 

    
    @Column(name="usurol_id", unique=true, nullable=false)
    public int getUsurolId() {
        return this.usurolId;
    }
    
    public void setUsurolId(int usurolId) {
        this.usurolId = usurolId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="rol_id", nullable=false)
    public Rol getRol() {
        return this.rol;
    }
    
    public void setRol(Rol rol) {
        this.rol = rol;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="usu_id", nullable=false)
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="usurol_fecharegistro", nullable=false, length=22)
    public Date getUsurolFecharegistro() {
        return this.usurolFecharegistro;
    }
    
    public void setUsurolFecharegistro(Date usurolFecharegistro) {
        this.usurolFecharegistro = usurolFecharegistro;
    }




}


